### ISSUE TITLE
queries failing on MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by brenhow** [davide-romanini/comictagger#103] opened 2018-01-18 00:07 UTC
I am trying to use ComicTagger on MacOS Sierra 10.12.6 and all queries are failing, either Auto-Tag or Search Online, even when I search for something as simple as Spider-Man. Is this a known issue?

Error message is "Archives with no matches: 1" for Auto-Tag and "No Matches Found" for "Search Online."

**Comment by gclicon** [comment] 2018-01-18 06:27
Were you able to get any queries to work? I'm able to get results with some queries but not all of them. Looks like it's an issue with the CV API. I found a recent post in the [CV forum](https://comicvine.gamespot.com/forums/api-developers-2334/searches-not-working-correctly-from-comicvine-scra-1922307/).

**Comment by davide-romanini** [comment] 2018-01-18 10:05
I'm pretty sure this is a duplicate of #97. I can search something like Ultimate Spiderman but not Spider-Man. It's not a Comictagger problem so I close the issue.

**Closed by davide-romanini** 2018-01-18 10:05 UTC
Labels: comicvine, duplicate

**Comment by gclicon** [comment] 2018-01-18 18:40
After some digging, I have a feeling it's not just a CV thing but I don't have any solid info to confirm. I was able to run different queries manually using postman and they all return data, so i'm not completely sold on it being CV. 

If I can figure it out, i'll add notes to #97.
