### ISSUE TITLE
Could not connect to ComicVine to search for series!

### ISSUE THREAD

**Issue by MarineKK** [davide-romanini/comictagger#87] opened 2017-03-24 14:12 UTC
I have not been able to use ComicTagger to Tag comics.  Every time I try to search I get "Could not connect to ComicVine to search for series!"  I have checked my comic vine key and it is still active.  But for some reason I am not able to connect still.

**Comment by Tec445** [comment] 2017-03-24 22:31
I am having this problem as well. Created a new ComicVine key just to be sure and that didn't work.

**Comment by fueledbysushis** [comment] 2017-03-25 00:58
I think the pb is that the new url is https://comicvine.gamespot.com/api/ but IDK where to change it

**Comment by benjec83** [comment] 2017-03-25 01:45
Also having this problem

**Comment by thegreenlantern71** [comment] 2017-03-25 03:41
This just started happening to me today as well.

**Comment by smaceslin** [comment] 2017-03-25 16:42
Just started happening here as well.  Anyone have any idea what is going on?

**Comment by Tec445** [comment] 2017-03-25 16:55
Another poster suggested that it was caused when comicvine changed their url. 
I am using the mac version of comictagger.  Is this happening with windows as well?

**Comment by smaceslin** [comment] 2017-03-25 17:19
Mac side here.

**Comment by oknoway** [comment] 2017-03-26 02:45
I have a hunch it's related to [ComicVine's switch to SSL](https://comicvine.gamespot.com/forums/api-developers-2334/notice-ssl-is-coming-be-ready-to-accept-ssl-video--1861940/#1)

I've changed the URL in source, but haven't been able to successfully compile the app for macOS…

**Comment by Pinostwon** [comment] 2017-03-29 21:29
Same for me. I download the source code and modified the URL file comictaggerlib\comicvinetalker.py (self.api_base_url = "https://comicvine.gamespot.com/api") according to another software that fixed the issue with the new url. 

However I don´t know how to compile the source code (I am Mac user) neither how to do this modification in a "compiled" version. Anyone with experience in coding can help?

**Comment by Tec445** [comment] 2017-04-01 15:59
Does anyone have an alternate method for adding tags on a Mac? I was using this on a daily basis so it's a total bummer to lose it.

**Comment by davide-romanini** [comment] 2017-04-01 22:18
I'm trying to figure out how to repackage all of it on my mac and was trapped in a long tail of downloads until the last one requires me to update MacOS...

**Comment by benjec83** [comment] 2017-04-01 23:02
Good luck! Windows user, and real sad this is out of action atm.

**Comment by SquaTront** [comment] 2017-04-02 18:15
Mac user here and I'm lost without this tool. Good luck in getting it compiled.

**Comment by Tec445** [comment] 2017-04-03 04:38
Thank you for creating this great app. Fingers crossed for a solution.

**Comment by benjec83** [comment] 2017-04-06 16:16
I'd be happy to throw some $ at it, and put it up on Fiver or something to see if someone can compile it for Windows

**Comment by WillPresley** [comment] 2017-04-06 17:29
Will also put $5 out there for a fresh compilation on Windows. If nobody can/does, I may take a stab myself this weekend, but can't until then.

**Comment by angryjonny** [comment] 2017-04-06 17:37
Same here but for a compiled Mac version. Happy to pay for this to happen sooner than later. Use this app a lot.

**Comment by davide-romanini** [comment] 2017-04-07 06:18
I'll take a look this weekend. Of course any help is appreciated, if you come with updates before me share with us!

**Comment by smaceslin** [comment] 2017-04-07 15:37
Thanks for keeping with this Davide-romanini!  Looking forward to positive results!!

**Comment by davide-romanini** [comment] 2017-04-07 18:00
I released a first dmg for MacOS. Please let me know if it works as expected. Thanks to @afuturefoe for the hints provided on issue #86!

**Comment by benjec83** [comment] 2017-04-07 18:02
@davide-romanini - if you can get windows working, I'm happy to give some $$ to you instead of putting it through Fiver. Love the app, happy to tip the maker

**Comment by afuturefoe** [comment] 2017-04-07 18:25
1.1.16-beta-rc seems to work fine for connecting to ComicVine. However, auto tag always returns no results. Auto-identify complains "Python Imaging Library (PIL) is not available and is needed for issue identification."

I had this issue on my machine and was able to remove it by commenting the following line

#from PIL import WebPImagePlugin

WebPImagePlugin is deprecated in PIL (and not used in ComicTagger as far as I can tell anyways)

**Comment by SquaTront** [comment] 2017-04-07 18:36
Won't launch in El Capitan 10.11.6.

**Comment by davide-romanini** [comment] 2017-04-07 19:28
Ok, I quickly changed the call on `getUrlContent`, but there are more place to change. @SquaTront: I built it on MacOS Sierra, because XCode refused to install on El Capitan. Surely there is some flag I don't know that solves the problem.
It appears I have some more work to do, but there's some hope at least :-) Thanks for your patience.

**Comment by Tec445** [comment] 2017-04-07 22:25
Thank you so much for spending your time on this. It's much appreciated. I have it working on my Mac now.
Unable to drag and drop files or auto tag though.

**Comment by smaceslin** [comment] 2017-04-09 12:31
Awesome work!  Thanks for all your efforts, it is much appreciated.

**Comment by ghjimmy** [comment] 2017-04-09 18:11
Perhaps I'm being a bit dim, but where are the pre-build dmg files for the mac released?
Thanks

**Comment by Tec445** [comment] 2017-04-09 23:49
I had some trouble with that as well. Click the tab that says "code"  and then the sub-tab that says "releases"

**Comment by angryjonny** [comment] 2017-04-10 01:07
Same here as @SquaTront, won't run in 10.11.6. It does launch in 10.12.4, but like @Tec445 when I drag any comic file or folder into the list window, I get a No Comic archives were found dialog box.

**Comment by afuturefoe** [comment] 2017-04-10 14:53
Yeah, drag-and-drop was broken for me too in the version I was working on, so I was using Open Folder. It's working for me in the latest beta (but that's the one with auto identification broken).

Completely stumped on why it won't run in El Capitan...

**Comment by thegreenlantern71** [comment] 2017-04-10 20:48
Happy to chip $ in as well to get Windows version working. :)

**Comment by benjec83** [comment] 2017-04-15 05:29
@davide-romanini Any luck with a Windows update?

**Comment by Tec445** [comment] 2017-04-16 20:12
Mac version Auto Identify returns the message:
 "Python Imaging Library (PIL) is not available and is needed for issue identification."

**Comment by angryjonny** [comment] 2017-04-16 20:54
Mac users are all getting the same @Tec445. I'm quite the noob but is there a way to replace the call for PIL with PILLOW instead? And I think this would fix the auto-tag function as well.

**Comment by angryjonny** [comment] 2017-04-17 13:44
@davide-romanini - And speaking for all us comic junkies, we REALLY appreciate your hard work!

**Comment by smaceslin** [comment] 2017-04-17 14:04
Let me echo angryjonny's comment.  Your work is very much appreciated.  Just being able to tag comics without having to manually enter all the information is a godsend!

**Comment by davide-romanini** [comment] 2017-04-17 15:08
@afuturefoe regarding older macOS X compatibility, I just read this: https://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible. It's a bit sad I think, for anyone running El Capitan seems the only easy option is to upgrade on Sierra. I also upgraded just to install the dev environment (XCode refused to install on El Capitan..).

**Comment by davide-romanini** [comment] 2017-04-17 15:23
Uploaded a new build: https://github.com/davide-romanini/comictagger/releases/tag/1.1.16-beta-rc2

**Comment by SquaTront** [comment] 2017-04-17 18:22
Thanks for updating this to work on the latest Mac OS. I will still hold out hope for a build that will run under El Capitan. I've been holding off on updating to that as it's troublesome in some areas. But thank you none the less!

**Comment by eduo** [comment] 2017-04-17 19:35
I just realized my iMac can't even be upgraded to Sierra (it's on El Capitan now). I was happily testing the build and couldn't understand why it wouldn't load. I'm so not used to not being on the latest version... :-(

**Comment by afuturefoe** [comment] 2017-04-17 21:06
1.1.16-beta-rc2 working on Sierra, including drag-and-drop and auto-identify/auto-tag.

**Comment by Tec445** [comment] 2017-04-17 21:08
Sweet! Thank you so much! Seems to be working great. In fact it seems faster/more responsive somehow.

**Comment by angryjonny** [comment] 2017-04-17 22:56
Oh hells Yeah! Back in business! Thanks bunches @davide-romanini. Auto-Tag, Drag-in-Drop, and all that jazz is working tip top on macOS 10.12.4

**Comment by ghjimmy** [comment] 2017-04-19 09:41
Having built the beta on El Capitan, I created a VM to try to build a version that would work on older releases.  However, it looks like rarlabs have broken their libunrar.so build with this latest release(5.5.2), so it won't  compile. Apart from the lack of unrar support, it looks like it does work, albeit with some warning messages on the console.  It won't be 32-bit, but apart from that it seems to work.  If I get the unrar issue solved, and there is interest, how could I upload the image so that people can use it?

**Comment by eduo** [comment] 2017-04-20 07:38
@ghjimmy Have you made a fork for it? You can apply your changes to a fork in Github and submit the changes to @davide-romanini for inclusion.

What changes did you make? I could replicate them for test purposes in an El Capitan and a Sierra machine in the meantime.

**Comment by ghjimmy** [comment] 2017-04-20 09:16
I literally changed 2 lines to remove the leading space from VERSION_STR in the two Makefiles.  Apart from that, I just compiled libunrar.so for Yosemite from the 4.5.4 source, copied it into the mac directory and then installed the needed packages for comictagger.  i.e.
- Xcode downloaded from the App store
- homebrew (https://brew.sh) - installed with the default settings
- Ran: `brew install cartr/qt4/pyqt@4`
- Downloaded the get-pip.py installer from http://pip.readthedocs.io/en/stable/installing
- Ran: `sudo python get-pip.py`
- Ran: `sudo pip install configparser ps4 pyinstaller pillow natsort PyPDF2 unrar pyobjc`
 

Then `cd mac; make` and the dmg for Yosemite is created.

I attempted to create a fork with the changes and then to upload my changes, but I'm a total novice to git (mercurial/svn/rcs/sccs user) so I'll need to read up exactly what to do.

However, I was just wanting to distribute the DMG file that I created for Yosemite so that other Mac users who cannot upgrade can get back to tagging successfully.

**Comment by eduo** [comment] 2017-04-21 21:25
Thanks. I was able to get it working. A few tweaks, though:

#For PyQT
brew tap cartr/qt4
brew tap-pin cartr/qt4
brew install pyqt@4
# Pip installs
pip install configparser pyinstaller pillow natsort PyPDF2 unrar pyobjc

For unrar I could use 5.3.11:
http://www.rarlab.com/rar/unrarsrc-5.3.11.tar.gz

I was able to compile but dropping files just doesn't work.

If you can zip and share your build I can place it in a fork and add the DMG if you wish. Otherwise just fork and upload the DMG to that fork (although if you upload your modifications you can push them here).

**Comment by SquaTront** [comment] 2017-04-22 16:02
I for one will be happy with any slightly working version running in El Capitan.

**Comment by ghjimmy** [comment] 2017-04-23 18:07
For those who want an older version, a Yosemite build which support all of the features of the beta2 release has been uploaded to https://github.com/ghjimmy/comictagger/releases/tag/1.1.16-bera-rc3

There have been no changes to the code, only a recompile and build under Yosemite.

**Comment by SquaTront** [comment] 2017-04-23 18:58
ghjimmy,
Thanks for the effort for an older compile, but it's crashing on launch in El Capitan. Any ideas of what to look for?

**Comment by ghjimmy** [comment] 2017-04-23 21:55
I've found an El Capitan machine, and have seen the problem.  It doesn't appear on Yosemite or Sierra using the same binary, but only El Capitan.  I'll see if I can see what's happening, but it seems to be exiting with an illegal instruction.  I'll try to investigate further.

**Comment by eduo** [comment] 2017-04-23 22:45
Is anybody unable to open cbz files on @ghjimmy's 1.1.16 beta RC3? I can open cbr and convert them to cbz but if I try loading the cbz directly it says the files don't seem to be comic files.

**Comment by davide-romanini** [comment] 2017-04-24 11:37
I started working on the Windows build: I managed to get the program working, but I stumbled upon a cx_freeze problem trying to build the installer.. For some reason it cannot find the module backports.configparser, that is perfectly installed and working by the way..

**Comment by benjec83** [comment] 2017-04-24 20:03
@davide-romanini I wonder if it's because of configparser.RawConfigParser - maybe RawConfigParser needs to be lower case too now?

**Comment by fandenivoldsk** [comment] 2017-05-08 20:08
@ghjimmy Any news on a pyinstaller fix for the El Capitan version? I really miss using Comictagger on my mac...

**Comment by ghjimmy** [comment] 2017-05-10 20:57
It wasn't a pyinstyaller issue, but a problem with the qt library.  So I created an El Capitan machine and built it on there and have released it as https://github.com/ghjimmy/comictagger/releases/tag/1.1.16-beta-rc4. Hopefully that'll allow people to start using it again.

**Comment by eduo** [comment] 2017-05-10 21:27
I'm not sure what is going on but both the newest release in Sierra and ghjimmy's version for El Capitan have a weird bug in my machine where if a file has a pound sign (#) in their name it won't import it in the list.

For example:

The Tick #01.cbz <- Won't import
The Tick #01.cbr <- Won't import
The Tick 01.cbz <- Will import
The Tick 01.cbr <- Will import
Do any of you have something like this happening?

**Comment by kopischke** [comment] 2017-05-10 21:30
@eduo I can confirm that issue for the RC2 on Sierra. Looks like `QUrl` needs some fragment escaping love.

**Comment by fandenivoldsk** [comment] 2017-05-10 21:40
Yes, I also got the '#' error in ghjimmy's El Capitan version. Also, although the Comic Vine API seems to be working, I am not able to match any comics with Comic Vine anymore. I get a 'No matches found!' error when using Auto-Identify option.

**Comment by fandenivoldsk** [comment] 2017-05-11 13:29
Well, the Comic Vine API worked today, so I guess the service was just down yesterday.
Hopefully the #-error will get fixed.

**Comment by ghjimmy** [comment] 2017-05-11 13:49
It looks like the '#' issue is only experienced with drag and drop.  If you use the open menu it seems to work.  OR it did for me on my El Capitan build when I tested it.  I don't have the other machines to test it on just now and I'll be offline for 10 days or do, so hopefully the Yosemite and El Capitan builds as supplied will suffice until I have time to look at the old build issues further.

Jimmy

**Comment by SquaTront** [comment] 2017-05-11 13:56
I too can verify that ghjimmy's build is running fine with Comic Vine in El Cap. I can also verify that the "#" error is gone when adding via the open menu. Thanks for the extra work on getting this running in El Capitan.

**Comment by eduo** [comment] 2017-05-11 14:23
Ah. I don't think I have ever in these many years used the "Open…" menu to open any file in Comictagger :D 

I tend to use drag and drop because I don't pick files from a single location. I'll have to get used to using the search function from the "Open…" dialog in the meantime.

(I tested and I can't drop files from multiple locations onto the "Open…" dialog, as is possible with files from a single directory).

Quick test: 
- Plain "Open…" dialog works for one or more files. Also for selecting files in list view from folders and subfolders.
- "Open…" dialog accepts dropped files from the finder for selection, but only in the same directory.
-"Open…" dialog allows search across directories and multiple selection for inclusion on the list, which is exactly what I needed.

Nice. Thanks.

**Comment by Deltron216** [comment] 2017-05-11 14:32
how about windows?

I'm not able to tag either...

**Comment by WillPresley** [comment] 2017-05-11 14:37
@Deltron216 This isn't a very helpful answer, but I was also out of luck on Windows (I attempted to build/fix comictagger for quite a while, whatever RAR libs are being used are trash, imo) and had to change things up pretty dramatically, but I'm back to tagging. I switched to using ComicRack + the Comic Vine Scraper plugin (https://github.com/cbanack/comic-vine-scraper) and I couldn't be happier.

I am going to keep trying to get this Windows version of comictagger working, but I've also gotten a little busy messing with openWMail (https://github.com/openWMail/openWMail)

**Comment by aniforprez** [comment] 2017-07-22 02:38
Same problem on windows. Nothing seems to be working right now

**Comment by digz-mctwist** [comment] 2017-07-22 15:39
Anyone had any luck compiling a fixed build for Windows?

**Comment by captaindooley** [comment] 2017-07-30 15:57
Just a heads up - 1.1.16-beta-rc2 didn't work for me on High Sierra beta, but 1.1.16-beta-rc4 did.

**Comment by MikeLkite** [comment] 2017-08-06 20:29
I presume the windows version is still shafted for now?

**Comment by aniforprez** [comment] 2017-08-07 07:39
There don't seem to be any new Windows builds so no it's still shafted for some reason

**Comment by tikilab** [comment] 2017-10-18 05:22
Did something change in the last few days with ComicVine? I am getting the "Could not connect to Comic Vine to search for series!" error. I logged into ComicVine and got the "prove you are a human" captcha but now I can log into the site fine and the page with my key says it's fine as well. I still can't connect with ComicTagger.

**Comment by SquaTront** [comment] 2017-10-18 14:05
On my mac running 1.1.16-beta-rc4 that was compiled for El Capitan, CT will not launch. Must be attempting a handshake with ComicVine and crapping out.

Joe

**Comment by afuturefoe** [comment] 2017-10-18 14:09
1.1.16-beta-rc4 confirmed working on High Sierra. If I remember correctly, rc4 has never worked on El Capitan, but there is a separate build here that is supposed to work on El Capitan: https://github.com/ghjimmy/comictagger/releases/tag/1.1.16-beta-rc4

**Comment by SquaTront** [comment] 2017-10-18 14:11
You are right, I’ll send ghjimmy the bug report. Thanks for pointing me in the right direction.

Joe

**Comment by Sparks01** [comment] 2017-11-12 16:54
Just wanted to add some notes. I'm using the El Capitan release of CT (https://github.com/ghjimmy/comictagger/releases/tag/1.1.16-beta-rc4) and suddenly it's become wildly inconsistent in how and when it connects to CV. 

Large batches are no trouble with AutoTag everything works as intended. The problem occurs when trying to ID individual files. Sometimes you can get it to work using Auto-Identify but others it won't and you get "Could not connect to Comic Vine to search for series" error. Trying "Search Online" when trying a single file doesn't work at all. 

Anyways, just wanted to add a little more detail here. 

Thanks for your help and work on this program.

**Comment by kabutocub** [comment] 2017-12-20 22:19
Is this project dead in terms of Windows? I know for a fact that people would be willing to donate to get a working version under Windows again.

**Comment by eduo** [comment] 2017-12-20 22:39
I'd recommend donating to thank for having been using the program rather than holding donations hostage, as that would be more of an incentive for developers to continue on it :)

**Comment by kabutocub** [comment] 2017-12-21 00:09
Although i get where you're coming from, I had only been using the program for like a month before it stopped working. I donate and register software very frequently, but i'm not charitable enough to donate for a software that I may never be able to use again.

**Comment by davide-romanini** [comment] 2017-12-21 11:31
I worked on the windows build some time ago, but the main stumble block I found if I remember correctly was related to cx_freeze not working as expected. Maybe a better solution is to use pyInstaller for all platforms. I would like to automate the builds with travis and appveyor. Unfortunely I have little time, so any help and contribution is welcome.

**Comment by davide-romanini** [comment] 2017-12-21 14:35
Opened a new epic issue for anything related to the build and release process: #94.
Closing this thread.

**Closed by davide-romanini** 2017-12-21 14:35 UTC

**Comment by davide-romanini** [comment] 2017-12-21 22:17
@kabutocub: I uploaded a windows (64bit) build made manually with pyInstaller (https://github.com/davide-romanini/comictagger/releases/download/1.1.16-beta-rc2/ComicTagger-1.1.16-beta-rc2-win-x86_64.zip). Just unzip the folder and launch comictagger.exe. I tested it on Seven and seems to work fine.
